"""add_follow_chart_tf_to_chart_indicators

Revision ID: 035d8520a235
Revises: 2b7cd0156ca6
Create Date: 2026-04-04 08:37:29.408508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035d8520a235'
down_revision: Union[str, None] = '2b7cd0156ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_indicators', sa.Column('follow_chart_tf', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_indicators', 'follow_chart_tf')
    # ### end Alembic commands ###
