"""add chart_indicators table

Revision ID: 2b7cd0156ca6
Revises: 108f2e33f9b1
Create Date: 2026-04-04 08:05:11.356392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b7cd0156ca6'
down_revision: Union[str, None] = '108f2e33f9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_type', sa.String(length=60), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('candles_ts_idx'), table_name='candles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('candles_ts_idx'), 'candles', [sa.literal_column('ts DESC')], unique=False)
    op.drop_table('chart_indicators')
    # ### end Alembic commands ###
